AllCops:
  NewCops: enable

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false
